[web]
super_user = "admin"
super_key = "12345678"
title = " ğŸ OaiT For OaiFree / FuClaude"
subtitle = "OaiT v1.2.0"
login_theme = "Retro Orange"
sidebar_state = "auto"
notice_enable = true
notice_title = "**æ¬¢è¿ä½¿ç”¨ï¼**"
notice_subtitle = "æœ¬æœåŠ¡åŸºäº@Neoçš„oaifreeæœåŠ¡ï¼Œç”±@Chenymeåˆ¶ä½œç™»å½•ç®¡ç†ç•Œé¢ï¼Œå¦‚æœè§‰å¾—å¥½ç”¨éº»çƒ¦ç»™ä¸ªStarå­ï¼  "
notice_size = "lg"
notice_radius = "sm"
notice_style = "outline"
notice_color = "dark"
notice_banner = true
Retro_Orange_notice = "<div style=\"text-align: center; font-family: 'Times New Roman', 'å®‹ä½“'; font-size: 15px;\">\n  <p style=\"font-size: 20px;\">æ¬¢è¿ä½¿ç”¨<strong> Chenyme-Oait </strong>æœåŠ¡</p>\n  <p style=\"font-size: 20px;\">ç‚¹å‡»<strong>å·¦ä¸Šè§’ç®­å¤´</strong>å¯è·å–æ›´å¤šæœåŠ¡å†…å®¹</p>\n</div>\n<div style=\"text-align: left;\">\n    <hr>\n    <p style=\"font-size: 30px;\"><strong>å…è´£å£°æ˜ / æœåŠ¡æ¡æ¬¾</strong></p>\n    <p style=\"font-size: 20px;\"><strong>1. æœ¬é¡¹ç›®å¼€å‘è€…ä¸å¯¹ä½¿ç”¨æœ¬é¡¹ç›®äº§ç”Ÿçš„ä»»ä½•åæœè´Ÿè´£ã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>2. æœ¬é¡¹ç›®ä¿ç•™éšæ—¶ä¿®æ”¹æˆ–ç»ˆæ­¢æœ¬ç«™ç‚¹çš„æƒåˆ©ï¼Œæ•ä¸å¦è¡Œé€šçŸ¥ã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>3. æœ¬é¡¹ç›®æ‰€æœ‰åŠŸèƒ½ä»…ä¾›å­¦ä¹ å’Œå¨±ä¹äº¤æµä½¿ç”¨ï¼Œä¸ä»£è¡¨å¾®è½¯çš„å®˜æ–¹è§‚ç‚¹æˆ–ç«‹åœºã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>4. æœ¬é¡¹ç›®ä¸å¯¹ä»»ä½•ç”±ä½¿ç”¨æœ¬é¡¹ç›®äº§ç”Ÿçš„ç›´æ¥æˆ–é—´æ¥æŸå¤±è´Ÿè´£ï¼ŒåŒ…æ‹¬ä½†ä¸é™äºæ•°æ®ä¸¢å¤±ã€ç³»ç»ŸæŸåã€æ³•å¾‹é£é™©ç­‰ã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>5. æœ¬é¡¹ç›®ä¸ä¿è¯æœ¬ç«™ç‚¹çš„åŠŸèƒ½å®Œæ•´æ€§ã€ç¨³å®šæ€§ã€å®‰å…¨æ€§å’Œå‡†ç¡®æ€§ï¼Œä¹Ÿä¸ä¿è¯æœ¬é¡¹ç›®ä¸OpenAIã€Claudeçš„ä¸€è‡´æ€§ã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>6. æœ¬é¡¹ç›®ä¸å¯¹æœ¬ç«™ç‚¹çš„å†…å®¹è¿›è¡Œå®¡æ ¸æˆ–ç›‘ç£ï¼Œç”¨æˆ·åº”è‡ªè¡Œæ‰¿æ‹…ä½¿ç”¨æœ¬ç«™ç‚¹çš„é£é™©å’Œè´£ä»»ã€‚</strong></p>\n    <p style=\"font-size: 20px;\"><strong>7. åœ¨ä¸­å›½å¤§é™†èŒƒå›´å†…ä½¿ç”¨è¯·éµå¾ªã€Šç”Ÿæˆå¼äººå·¥æ™ºèƒ½æœåŠ¡ç®¡ç†æš‚è¡ŒåŠæ³•ã€‹çš„è¦æ±‚ï¼Œè¯·å‹¿å¯¹ä¸­å›½åœ°åŒºå…¬ä¼—æä¾›ä¸€åˆ‡æœªç»å¤‡æ¡ˆçš„ç”Ÿæˆå¼äººå·¥æ™ºèƒ½æœåŠ¡ã€‚</strong></p>\n    <p style=\"font-size:20px;\"><strong>8. è¯·è‡ªè§‰éµå®ˆé“å¾·è§„èŒƒï¼Œæ–‡æ˜ä½¿ç”¨ï¼Œç¦æ­¢è¾“å…¥è‰²æƒ…ã€æš´åŠ›ã€ææ€–ç­‰è¿æ³•çŠ¯ç½ªå†…å®¹ï¼Œä¸€ç»å‘ç°ï¼Œç«‹å³å°ç¦ï¼Œå¹¶æ°¸ä¹…æ‹‰é»‘ï¼è‹¥æœ‰ä»»ä½•å¯¼è‡´è¿æ³•çŠ¯ç½ªè¡Œä¸ºï¼Œç”¨æˆ·åº”è‡ªè¡Œæ‰¿æ‹…ä½¿ç”¨æœ¬ç«™ç‚¹çš„é£é™©å’Œè´£ä»»ã€‚</strong></p>\n  <hr>\n  <p style=\"font-size: 25px;\"><strong> OpenAIï¼ŒNot CloseAI </strong></p>\n  <p style=\"font-size: 25px;\"><strong> ChatGPT/Claude can make mistakes. Check important info.</strong></p>\n  <p style=\"font-size: 25px;\"><strong>æ„¿ç§‘æŠ€æ— å›½ç•Œï¼Œå¼€æºç²¾ç¥æ°¸å­˜ </strong></p>\n</div>\n\n"
refresh_all = true
readme = false
user_refresh = false
invite_link_enable = false
invite_link = "https://"
refresh_link_enable = false
refresh_link = "https://"
share = true
share_notice = "**è¯·è‡ªè§‰éµå®ˆé“å¾·è§„èŒƒï¼Œæ–‡æ˜ä½¿ç”¨ï¼Œç¦æ­¢è¾“å…¥è‰²æƒ…ã€æš´åŠ›ã€ææ€–ç­‰è¿æ³•å†…å®¹ï¼Œä¸€ç»å‘ç°ï¼Œç«‹å³å°ç¦ï¼**"

[domain]
choose_domain = "ä¸å…è®¸"
domain_default_openai = "new.oaifree.com"
domain_default_anthropic = "ä¸å¯ç”¨"
domain_select = true

[excel]
hide_index_account = true
height_account = 248
order_what_account = "ç”¨æˆ·ç»„"
order_row_account = "é»˜è®¤"
order_account = [ "ç”¨æˆ·ç»„", "æœåŠ¡å•†", "è®¢é˜…ç±»å‹", "è´¦æˆ·é‚®ç®±", "AC_Token", "RF_Token",]
hide_index_invite = true
height_invite = 248
order_what_invite = "æ˜¯å¦ä½¿ç”¨"
order_row_invite = "é»˜è®¤"
order_invite = [ "Invite_Token", "OpenAI_ç”¨æˆ·ç»„", "Anthropic_ç”¨æˆ·ç»„", "ChatGPT", "Claude", "æ˜¯å¦ä½¿ç”¨", "å¤‡æ³¨",]
hide_index_user = true
height_user = 248
order_what_user = "è´¦æˆ·"
order_row_user = "é»˜è®¤"
order_user = [ "è´¦æˆ·", "å¯†ç ", "UID", "ChatGPT", "Claude", "å¤‡æ³¨",]
hide_index_oaifree = true
height_oaifree = 448
order_what_oaifree = "è´¦æˆ·"
order_row_oaifree = "é»˜è®¤"
order_oaifree = [ "è´¦æˆ·", "SA_Token", "ç”¨æˆ·ç»„", "è®¢é˜…ç±»å‹", "é™åˆ¶ç½‘ç«™", "è¿‡æœŸç§’æ•°", "GPT3.5é™åˆ¶", "GPT4é™åˆ¶", "ä¼šè¯æ— éœ€éš”ç¦»",]
hide_index_fuclaude = true
height_fuclaude = 448
order_what_fuclaude = "è´¦æˆ·"
order_row_fuclaude = "é»˜è®¤"
order_fuclaude = [ "è´¦æˆ·", "ç”¨æˆ·ç»„", "SE_Token", "è®¢é˜…ç±»å‹",]
hide_index_refresh = true
height_refresh = 248
order_what_refresh = "ç”¨æˆ·ç»„"
order_row_refresh = "é»˜è®¤"
order_refresh = [ "userRF_Token", "ç”¨æˆ·ç»„", "é™åˆ¶ç½‘ç«™", "è¿‡æœŸç§’æ•°", "GPT3.5é™åˆ¶", "GPT4é™åˆ¶", "ä¼šè¯æ— éœ€éš”ç¦»", "å¤‡æ³¨", "æ˜¯å¦ä½¿ç”¨",]

[new]
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
set1 = ""
set2 = ""
set3 = ""
set4 = ""
set5 = ""

[chart]
start_date = 2024-07-13
end_date = 2024-07-13
height = 400
horizontal = true
