[web]
readme = false
login_Theme = "free"
button_style = "Classic-black"
button_border = "#FFF"
button_border_radius = 5
title = " ğŸ OaiT For OaiFree"
subtitle = "OaiT v1.1.4"
domain = "new.oaifree.com"
choose_domain = "å…è®¸"
user_domain = [ "new.oaifree.com", "demo.oaifree.com",]
notice_enable = true
notice_title = "**æ¬¢è¿ä½¿ç”¨ï¼**"
notice_subtitle = "æœ¬æœåŠ¡åŸºäº@Neoçš„oaifreeæœåŠ¡ï¼Œç”±@Chenymeåˆ¶ä½œç™»å½•ç®¡ç†ç•Œé¢ï¼Œå¦‚æœè§‰å¾—å¥½ç”¨éº»çƒ¦ç»™ä¸ªStarå­ï¼  "
notice_size = "lg"
notice_radius = "sm"
notice_style = "outline"
notice_color = "dark"
notice_banner = true
super_user = "admin"
super_key = "12345678"
user_refresh = false
refresh_all = true
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
share = false
share_notice = "**è¯·è‡ªè§‰éµå®ˆé“å¾·è§„èŒƒï¼Œæ–‡æ˜ä½¿ç”¨ï¼Œç¦æ­¢è¾“å…¥è‰²æƒ…ã€æš´åŠ›ã€ææ€–ç­‰è¿æ³•å†…å®¹ï¼Œä¸€ç»å‘ç°ï¼Œç«‹å³å°ç¦ï¼**"
invite_link_enable = false
invite_link = "https://"
refresh_link_enable = false
refresh_link = "https://"

[excel]
hide_index_account = true
height_account = 248
order_what_account = "ç”¨æˆ·ç»„"
order_row_account = "é»˜è®¤"
order_account = [ "ç”¨æˆ·ç»„", "è®¢é˜…ç±»å‹", "è´¦æˆ·é‚®ç®±", "AC_Token", "RF_Token",]
hide_index_invite = true
height_invite = 248
order_what_invite = "æ˜¯å¦ä½¿ç”¨"
order_row_invite = "é»˜è®¤"
order_invite = [ "Invite_Token", "ç”¨æˆ·ç»„", "å¤‡æ³¨", "æ˜¯å¦ä½¿ç”¨",]
hide_index_user = true
height_user = 248
order_what_user = "ç”¨æˆ·ç»„"
order_row_user = "é»˜è®¤"
order_user = [ "è´¦æˆ·", "å¯†ç ", "UID", "SA_Token", "ç”¨æˆ·ç»„", "è®¢é˜…ç±»å‹",]
hide_index_refresh = true
height_refresh = 248
order_what_refresh = "ç”¨æˆ·ç»„"
order_row_refresh = "é»˜è®¤"
order_refresh = [ "userRF_Token", "ç”¨æˆ·ç»„", "é™åˆ¶ç½‘ç«™", "è¿‡æœŸç§’æ•°", "GPT3.5é™åˆ¶", "GPT4é™åˆ¶", "ä¼šè¯æ— éœ€éš”ç¦»", "å¤‡æ³¨", "æ˜¯å¦ä½¿ç”¨",]

[chart]
start_date = 2024-07-01
end_date = 2024-07-01
height = 400
horizontal = false
